// <auto-generated />
using System;
using BAP.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BAP.Db.Migrations
{
    [DbContext(typeof(ButtonContext))]
    [Migration("20210818200002_Md5HashOnFirmwareInfo")]
    partial class Md5HashOnFirmwareInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");

            modelBuilder.Entity("BapDb.FirmwareInfo", b =>
                {
                    b.Property<int>("FirmwareInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLatestVersion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Md5Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FirmwareInfoId");

                    b.ToTable("FirmwareInfos");
                });

            modelBuilder.Entity("BapDb.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BapDb.GamePlayLog", b =>
                {
                    b.Property<int>("GamePlayLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("GamePlayLogId");

                    b.HasIndex("GameId");

                    b.ToTable("GamePlayLog");
                });

            modelBuilder.Entity("BapDb.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RelateiveScore")
                        .HasColumnType("int");

                    b.Property<string>("ScoreInfoJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ScoreId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("BapDb.GamePlayLog", b =>
                {
                    b.HasOne("BapDb.Game", "Game")
                        .WithMany("GamePlayLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BapDb.Game", b =>
                {
                    b.Navigation("GamePlayLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
