// <auto-generated />
using System;
using BAP.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BAP.Db.Migrations
{
    [DbContext(typeof(ButtonContext))]
    [Migration("20210822043451_gamefavsAndGameLog")]
    partial class gamefavsAndGameLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");

            modelBuilder.Entity("BapDb.FirmwareInfo", b =>
                {
                    b.Property<int>("FirmwareInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLatestVersion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Md5Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FirmwareInfoId");

                    b.ToTable("FirmwareInfos");
                });

            modelBuilder.Entity("BapDb.GameFavorite", b =>
                {
                    b.Property<int>("GameFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameUniqueId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GameFavoriteId");

                    b.HasIndex("GameUniqueId")
                        .IsUnique();

                    b.ToTable("GameFavorites");
                });

            modelBuilder.Entity("BapDb.GamePlayLog", b =>
                {
                    b.Property<int>("GamePlayLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateGameSelectedUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameUniqueId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("GamePlayLogId");

                    b.ToTable("GamePlayLog");
                });

            modelBuilder.Entity("BapDb.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RelateiveScore")
                        .HasColumnType("int");

                    b.Property<string>("ScoreInfoJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ScoreId");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
