// <auto-generated />
using System;
using BAP.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAP.Db.Migrations
{
    [DbContext(typeof(ButtonContext))]
    [Migration("20230125065213_AddingProviders")]
    partial class AddingProviders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BAP.Db.ActiveProvider", b =>
                {
                    b.Property<int>("ActiveProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateActivated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderInterfaceFullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderUniqueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ActiveProviderId");

                    b.ToTable("ActiveProviders");
                });

            modelBuilder.Entity("BAP.Db.FirmwareInfo", b =>
                {
                    b.Property<int>("FirmwareInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLatestVersion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Md5Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FirmwareInfoId");

                    b.ToTable("FirmwareInfos");
                });

            modelBuilder.Entity("BAP.Db.GameFavorite", b =>
                {
                    b.Property<int>("GameFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameUniqueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GameFavoriteId");

                    b.HasIndex("GameUniqueId")
                        .IsUnique();

                    b.ToTable("GameFavorites");
                });

            modelBuilder.Entity("BAP.Db.GamePlayLog", b =>
                {
                    b.Property<int>("GamePlayLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateGameSelectedUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameUniqueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GamePlayLogId");

                    b.ToTable("GamePlayLogs");
                });

            modelBuilder.Entity("BAP.Db.GameStorage", b =>
                {
                    b.Property<int>("GameStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameUniqueId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("GameStorageId");

                    b.HasIndex("GameUniqueId")
                        .IsUnique();

                    b.ToTable("GameStorageVault");
                });

            modelBuilder.Entity("BAP.Db.MenuItemStatus", b =>
                {
                    b.Property<int>("MenuItemStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MenuItemUniqueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInMainMenu")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MenuItemStatusId");

                    b.ToTable("MenuItemStatuses");
                });

            modelBuilder.Entity("BAP.Types.ButtonLayout", b =>
                {
                    b.Property<int>("ButtonLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalButtons")
                        .HasColumnType("int");

                    b.HasKey("ButtonLayoutId");

                    b.ToTable("ButtonLayouts");
                });

            modelBuilder.Entity("BAP.Types.ButtonLayoutHistory", b =>
                {
                    b.Property<int>("ButtonLayoutHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ButtonLayoutId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUsed")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ButtonLayoutHistoryId");

                    b.HasIndex("ButtonLayoutId");

                    b.ToTable("ButtonLayoutHistories");
                });

            modelBuilder.Entity("BAP.Types.ButtonPosition", b =>
                {
                    b.Property<int>("ButtonPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ButtonId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ButtonLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.HasKey("ButtonPositionId");

                    b.HasIndex("ButtonLayoutId");

                    b.ToTable("ButtonPositions");
                });

            modelBuilder.Entity("BAP.Types.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DifficultyDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DifficultyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NormalizedScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ScoreData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ScoreDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ScoreId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("BAP.Types.ButtonLayoutHistory", b =>
                {
                    b.HasOne("BAP.Types.ButtonLayout", "ButtonLayout")
                        .WithMany("ButtonLayoutHistories")
                        .HasForeignKey("ButtonLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ButtonLayout");
                });

            modelBuilder.Entity("BAP.Types.ButtonPosition", b =>
                {
                    b.HasOne("BAP.Types.ButtonLayout", "ButtonLayout")
                        .WithMany("ButtonPositions")
                        .HasForeignKey("ButtonLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ButtonLayout");
                });

            modelBuilder.Entity("BAP.Types.ButtonLayout", b =>
                {
                    b.Navigation("ButtonLayoutHistories");

                    b.Navigation("ButtonPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
