version: '2.4'
networks:
  tinker:
    driver: bridge
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
     - 1883:1883
    networks:
     - tinker
    volumes:
      - ./mosquitto/:/mosquitto
  blazor:
    hostname: blazor
    container_name: blazor
    image: ghcr.io/ngelotte/tinkerbutton/tinker-button-blazor-image-arm:latest
    restart: unless-stopped
    environment:
      - "TZ=America/Los_Angeles" 
      - MosquittoAddress=mosquitto
      - mySqlPass="${mySqlPassword}"
    volumes:  
      - ./blazor-data:/data
    networks:
    - tinker
    ports:
     - 80:80
  db:
    hostname: thwackdb
    container_name: thwackdb
    image: jsurf/rpi-mariadb:latest
    restart: unless-stopped
    networks:
     - tinker
    environment:
      MYSQL_ROOT_PASSWORD: ${mySqlPassword}
    volumes:  
      - ./mariaDbData:/var/lib/mysql