version: '2.1'
networks:
    tinker:
       driver: bridge
volumes:
    mosquitto:
    mariaDbData:
    blazor-data:
    
services:
  # balena-mdns-publisher:
    # image: 'balena/balena-mdns-publisher:master'
    # network_mode: host
    # cap_add:
        # - SYS_RESOURCE
        # - SYS_ADMIN
    # security_opt:
        # - 'apparmor:unconfined'
    # tmpfs:
        # - /run
        # - /sys/fs/cgroup
    # labels:
        # io.balena.features.dbus: '1'
    # environment:
        # CONFD_BACKEND: ENV
        # MDNS_TLD: local
        # MDNS_SUBDOMAINS: >-
            # ["bap"]
  opentts:
    image: synesthesiam/opentts:es
    hostname: opentts
    container_name: opentts
    restart: unless-stopped
    ports:
     - 5500:5500
    networks:
     - tinker
  mosquitto:
    build: Mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
     - 1883:1883
    networks:
     - tinker
  bapwebapp:
    restart: unless-stopped
    depends_on:
      - db
      - mosquitto
      - opentts
    environment:
      - "TZ=America/Los_Angeles" 
      - MosquittoAddress=mosquitto
      - "DbConnectionString=server=db;database=buttons;user=root;password=10640b03-1020-4be6-a065-634ea64c33c4"
    build: .
    volumes:  
      - 'blazor-data:/data'
    networks:
    - tinker
    ports:
     - 80:8080
    labels:
      io.balena.features.supervisor-api: '1'
  wifictrl:
    build: WifiControl
    restart: unless-stopped
    environment:
      AP_SSID: BAPButton
      AP_PASSWORD: B@pB@p1234
      WIFI_SSID: home
      WIFI_PASSWORD: NickAndLiesl
    labels:
      io.balena.features.dbus: '1'
    networks:
     - tinker
  db:
    image: tobi312/rpi-mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 10640b03-1020-4be6-a065-634ea64c33c4
    volumes:  
      - 'mariaDbData:/var/lib/mysql'
    networks:
     - tinker
